# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  flutter: circleci/flutter@1.0.0
  discord: antonioned/discord@0.1.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  discord-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - discord/status:
          webhook: https://discord.com/api/webhooks/911480591680151552/d0EtmdQDkJg83_MQt8LugU2dpAltmDsRlVPxY30EEhX1qzHggVVefxgj8k63KK8caeX1 
          success_message: Job Success 
          failure_message: Job Failed 

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  flutter-workflow:
    jobs:
      - flutter/lint:
          version: '2.5.3'
      - discord-job
